# Generated by Django 5.1.2 on 2024-10-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_alter_lesson_options_rename_name_course_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('order_in_module', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('order', 'course')},
        ),
    ]
